name: Test Compiler Bug

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # This uses Xcode 15
          - os: macos-14
          # This uses Xcode 16 (broken)
          - os: macos-15
          # This uses Xcode 16.1 (broken)
          - os: macos-15
            xcode: 16.1
          # This uses Xcode 16.2 (fixed)
          - os: macos-15
            xcode: 16.2

          # This uses Xcode 16, with constraint elimination off
          - os: macos-15
            cflags: "-mllvm -enable-constraint-elimination=0"

          # Use open source clang
          - os: macos-15
            clang: llvm@17
          - os: macos-15
            clang: llvm@18
          - os: macos-15
            clang: llvm@19

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        if: matrix.xcode != ''
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Test Compiler Bug
        run: |
          export CLANG="clang"
          export CC=""
          export CFLAGS=""

          if [[ "${{ matrix.clang }}" != "" ]]; then
            echo '::group::Install LLVM'
            brew install --quiet ${{ matrix.clang }}
            export CLANG="/opt/homebrew/opt/${{ matrix.clang }}/bin/clang"
            export CC="CC=$CLANG"
            echo '::endgroup::'
          fi
          echo '::group::Clang version'
          $CLANG --version
          echo '::endgroup::'

          make test $CC CFLAGS="${{ matrix.cflags }}"
